<template>
  <div>
    <h1>このサイトについて</h1>
    <p>
      作者：
      <a
        href="https://twitter.com/Shift_Petta"
        target="_blank"
      >
        Shift_Petta
      </a>
    </p>
    <p>今期放送アニメを自動取得し、好きなように自分の心のコインを設定して表示するだけのアプリです。</p>
    <p>
      このアプリは
      <a
        href="https://github.com/Project-ShangriLa/sora-playframework-scala"
        target="_blank"
      >Shangrila Anime API</a> を使用して作成されています。
    </p>
    <p>
      何か連絡がある場合はTwitterまでお願いします。
    </p>
    <p>
      ※当サイトはジョークサイトです。サイト内の「コイン」は現実社会の如何なる通貨、電子マネー、暗号資産、その他金融商品等とは一切の関連がありません。予めご了承ください。
    </p>
    <a href="/">戻る</a>
  </div>
</template>
